[pytest]
; addopts = -q --disable-warnings --cov=prob --cov-report=term-missing:skip-covered
markers =
    legacy: mark test as legacy, to be skipped in the future
    smoke: mark test as smoke test
    slow: mark test as slow, to be skipped in fast runs
    gpu: mark test as requiring GPU
    cpu: mark test as requiring CPU only
    integration: mark test as integration test
addopts = --cov=prob --cov-report=term-missing:skip-covered -m "not legacy"
; testpaths = prob/tests
filterwarnings =
    ignore::DeprecationWarning