[pytest]
; addopts = -q --disable-warnings --cov=prob --cov-report=term-missing:skip-covered
addopts = --cov=prob --cov-report=term-missing:skip-covered
; testpaths = prob/tests
filterwarnings =
    ignore::DeprecationWarning